### ISSUE TITLE
ELAN1203 problems

### ISSUE THREAD

**Issue by animator013** [VoodooI2C/VoodooI2C#190]
Hi there,

installed latest kext version 2.1.6 + sattelite kext VoodooI2CCHID. My ELAN1203 works but there are these quirks:

- left button and right button works only when i am touching the trackpad and right button does the same thing as left button :)

I've made dsdt patching according to guide.

Can you help me with this ? What do you need from me to provide ?

**Comment by animator013** [comment]
Ah, it seems i did it wrong.

Tried to do it again on ETPD device. After inserting GPIO pin list to 0x47 as my APIC is 0x5f i get Busy timeout ETPD in logs...

What to do ?

**Comment by ben9923** [comment]
Notice GPIO interrupts are not yet supported in CFL+. Pin calculation is also different.
Please ask for help in the Gitter chat, attach your files as noted [here](https://voodooi2c.github.io/#Troubleshooting) and [here](https://voodooi2c.github.io/#Common%20Errors).

**Comment by animator013** [comment]
Ok, posted there. Thank you, hope it can be solved.

**Comment by williambj1** [comment]
Same Issue:
Physical buttons only work when there is at least one finger on the trackpad.
When using physical buttons to highlight words, it behaves like continuing for a few seconds then it suddenly breaks which makes it impossible to use.

**Comment by animator013** [comment]
Exactly the same thing.

**Comment by williambj1** [comment]
### Video

![1](https://user-images.githubusercontent.com/45396585/57981731-44286500-7a6e-11e9-8075-51dac4409a6e.gif)

**Comment by blankmac** [comment]
The button behavior isn't entirely unexpected.  Think of it this way, the MT2 that we are simulating is an integrated one-button touchpad device.  You can't actuate the button without being in contact with it and since it is only one button, there are no left/right click methods *other* than the options contained in the trackpad system preference pane.  Unfortunately, this doesn't translate well to devices that have separate physical buttons.  I'm not sure what the solution would be other than to address specific devices with the problem.

As for the selection behavior, try this so we can see if the two issues are related -- with one finger, move the cursor into position to select some text, leave that finger in place as an anchor, click/hold your physical button, and then use an additional finger to drag/select while leaving the first finger in place and see if it's still the same.  (unless that's what you're already doing, of course)

**Comment by LeeBinder** [comment]
These issues (and one more) are the reason I'm still using v.2.0.3 and am running High Sierra (because 2.0.3 is not Mojave compatible). To me the switch to MT2 was a HUGE regression.

**Comment by kprinssu** [comment]
Please note that this will probably will not be supported due to use interfacing directly with macOS (original Apple hardware do not have physical buttons and we will not support it in VoodooI2C). Please contact the VoodooInput devs and get support in the upstream repo.

If you have any issues related to VoodooI2C itself, please create a new ticket.

**Comment by williambj1** [comment]
This issue was solved by Goshin in v2.4.1, thumbs up!
